### ISSUE TITLE
Check on Scheme 7, the formation of sulfonic ester

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#1]
File is uploaded as [Fig7.eps](https://github.com/opensourcecatalysis/OPS-Paper1/blob/master/Figures/Fig7.eps) and Figure 7 v2.cdx.
Separately to a discussion of whether this is reasonable, is this figure accurately describing what we intend?

**Comment by paulking1995** [comment]
Looks correct to me.
