### ISSUE TITLE
Fix yield of compound 20

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#11]
See comment in paper.

**Comment by mattodd** [comment]
Both the paper and Fig 4 now say that this compound was formed in 75 and 87% yield, so did someone fix this already? We can close this Issue?

**Comment by paulking1995** [comment]
One is for when the dimethyl acetal is used while the other is when the ketone (cyclohexanone) is used. It is clarified in the Figure legend.

There is no issue here.
