### ISSUE TITLE
Interpretation of energy barriers to carbocation formation

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#17]
Question for Bun on how we talk about the computational modeling section. Will take up by email in first instance.

**Comment by mattodd** [comment]
@edwintse @katb I may have asked this before, but can we generate a PDF of the paper with the schemes included? I think not, right? Was hoping to send the updated paper to Bun. Is it easiest to send the scheme-less PDF to him plus the relevant figure as a separate file?

**Comment by edwintse** [comment]
Done and sent.

**Comment by mattodd** [comment]
Bun has replied by email "With the Fig, I guess I calculated the process exactly as depicted: protonation followed by ring opening.  In all cases, the energy change for ring opening is small, such that the process is limited by preceding protonation.  The energies that correspond to the second step are: +6.9 (for 11), -23.5 (3), -15.7 (17) and -23.2 (22).  May be one can put those in but then focus the discussion on protonation?" Makes sense. Have asked him to add text directly to ensure he's happy. Will close this issue once the text is in.

**Comment by mattodd** [comment]
Let's add a note to the paper in the legend to Fig 11 that says "(Interestingly the energy change for ring opening is small, such that the process is limited by preceding protonation. The energies that correspond to the second step are: +6.9 (for 11), -23.5 (3), -15.7 (17) and -23.2 (22).)"

**Comment by mattodd** [comment]
Closing this, but we must ensure that we run this past Bun (which we will do as part of submission in any case).
