### ISSUE TITLE
HPLC Assay for e.e. in SI?

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#18]
Is the description of the HPLC assay for monitoring the ee of the isochromans in the SI? If yes, close. If no, add with consensus from everyone who has used it. Must ensure consistency if there are any variants of the conditions.

**Comment by mattodd** [comment]
@paulking1995 I'm guessing you can generate this, given that you're currently doing it.

**Comment by paulking1995** [comment]
Added this to "S1 Text.docx"

The enantiomeric excess was determined by chiral HPLC was performed on an X equipped with Chiracel OD-H (75:25 hexane:i-PrOH, 0.7 mL/min, λ = Y nm) t(r) = 18.0, 22.3 min.

I will need to fill in X and Y once I check the details for that.

**Comment by paulking1995** [comment]
Done
