### ISSUE TITLE
Reorder bibitems in bibliography section to match the callout order

### ISSUE THREAD

**Issue by katb** [opensourcecatalysis/OPS-Paper1#19]

**Comment by mattodd** [comment]
Who's doing this?

**Comment by edwintse** [comment]
Reordered the last few bibitems as per their callout order. Added dois for those missing.

Leaving this open for now incase there are more references to be added.

**Comment by mattodd** [comment]
If this is needed we can deal with it as the final step. Closing for now just to clear old issues.
