### ISSUE TITLE
Previous attempts to isolate sulfonic esters

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#2]
Paul - related to #1  - we attempted to isolate products from the reaction that appeared to suffer from acid consumption, products that might have included the sulfonic ester if it was being made. What was the outcome, and what were the links to the relevant experiments on the ELN?

**Comment by paulking1995** [comment]
PK4-32: Attempt to isolate interaction of aldehyde with the butanol by refluxing the aldehyde with the acid before running the reaction.
PK4-34: Attempt to isolate interaction of alcohol with the butanol by refluxing the aldehyde with the acid before running the reaction.

Neither suggest that one of the starting materials or acid is disintegrating but rather, the reaction stalls by some form of product inhibition (which is a common problem in catalysis).
