### ISSUE TITLE
The “Do We Need These” figure

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#20]
@katb there’s a picture file of two compounds in the “old” folder that predate your move to Oxford (KAB133-1 and KAB141-1). They are not in the paper. Should they be? Do we need these data? Do you have them written up anywhere?

**Comment by edwintse** [comment]
Not needed for the paper. Not mentioned in @katb's thesis either. Can keep it in the Old folder.
