### ISSUE TITLE
Check on Structure Tally

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#21]
The following compounds in the structure tally are not in the SI. In each case can we confirm the following reasons?

6. Commercial?
8. Commerical?
13. Commercial?
14. Not isolated, right?
27. Not isolated, right?
28. Commercial?
29. Not isolated, right?
30. Not isolated, right?
33. Not isolated, right?

**Comment by edwintse** [comment]
@mattodd Not sure if the compound numbers match what you think they are (e.g. 10 is 2-phenylethanol).

I've added a legend to the Compound Numbering.cdx file to colour coordinate compounds being commercial/known/novel/not isolated.

6, 8, 10, 13 are all commercial.
7, 9 are known and are already in S1 Text
11 was not isolated (no reaction)
12, 14 are novel compounds and are already in S1 Text

**Comment by mattodd** [comment]
Not seeing any change to the Compound Numbering.cdx file - check your Dropbox sync?

**Comment by edwintse** [comment]
Whoops, should be synced now.

**Comment by mattodd** [comment]
This is great. @katb it'd be very useful if you could add 35-38 from your scheme to this file (Compound Numbering), so we have everything together and can easily generate strings. I don't have your chemdraw.

**Comment by mattodd** [comment]
Complete - the chemdraw now contains these, so closing.
