### ISSUE TITLE
Clarification of files in the SI folder

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#23]
There are 4 .eps files in the SI folder that need removing or renaming:

Figure S NMR Assay Compound 1 - 1H of standard product. Go into SI? If yes, add and move file to Old
Figure S NMR Assay Compound 2 - 13C ditto?
Figure S NMR Assay Compound 3 - same as current Figure S3? If yes move to Old
Figure S NMR Assay Compound 4 - same as current Figure S4? If yes move to Old

There are two Figure S2’s. Can one be moved to Old?

Where are these going?
S1_table
S1_table.pdf
S2_fig (NMR Curve).eps
S3_fig.eps

**Comment by edwintse** [comment]
@mattodd Should we add entries for the GC and NMR standard curves? (currently called GC Standard Curve and NMR Standard Curve)

Figure S NMR Assay Compound 1/2 have been added to S1_Text and have been moved to Old

Figure S NMR Assay Compound 3 moved to Old.
Figure S NMR Assay Compound 4 moved to Old.

"Figure S2 maybe NMR Standard Curve" and "S2_fig (NMR Curve)" have been moved to Old. "Figure S2" has been renamed to "S2_Fig".

"S1_table" renamed to "S1_Table"
"S1_table.pdf" moved to Old

"GC and NMR Assays" moved to Old (already described in main text)

"Data from Merck" renamed "S1_Appendix" and added to the SI list

**Comment by mattodd** [comment]
Closing since number of duplicate/legacy files now small.
