### ISSUE TITLE
Solvent Survey

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#26]
Original issue: Need publication-ready version of the sheet that surveys solvent, for SI (so not super-pretty, but ready). This also needs updating.

This is better as a Google sheet, to which people can add data - this would be an important part of our establishing a community resource. Perhaps as a separate tab in the online sheet is easiest. Ed - you’re going to have to update this for the last 2 years. We can include a column for publication year and one for DOI.

Ed I think you’ve done this to your own satisfaction, right?  As a tab in the online sheet? If so, close this issue.

**Comment by edwintse** [comment]
Solvent survey completed and updated as a new page in the existing Google sheet.
