### ISSUE TITLE
Figure S1 is old and needs an update

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#27]
Who made the current Figure S1? Is it ready to go?

**Comment by mattodd** [comment]
I have renamed "GC Standard Curve.eps" "Figure S1" on Dropbox. I need it confirmed that this is the correct figure here - i.e. that the gradient is correct.

**Comment by paulking1995** [comment]
Yes, it's the correct GC curve - and the gradient is correct.

Closed.
