### ISSUE TITLE
Check on the NMR gradient

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#28]
NMR gradient. Is nearer 1. Need to alter the paper’s procedure. Comparison: update that the comparison (GC:NMR) works.

Is the NMR assay description correct, @paulking1995 ? Can we close this? See "OPS1#7" in four places in the paper.

**Comment by mattodd** [comment]
All occurrences of "OPS1#7" still need dealing with @paulking1995 . Replaced in Overleaf with "GHI#28"

**Comment by mattodd** [comment]
@paulking1995 you put comments related to this in #9 (which I've now closed). So:

1) For the equation/yield: OK. No action needed.

2) I've simplified the text referring to our recommendations for purity (in paragraph starting “The GC and NMR assays…”). If we are advocating a use of qNMR then we ought to have done that, but haven't. So I've made that more generic, which is fine for our purposes. No action needed.

3) NMR graph still needs fixing. We have two mutually incompatible figures in the SI, where we can only have one. The current figure ("S2_Fig.eps") is the better one that we need, but its gradient does not match the other figure ("NMR Standard Curve.eps"). This needs fixing so that we have one SI figure, and the other(s) is/are shifted to the "old" folder.

4) The paragraphs still duplicate. @paulking1995 please merge these into one paragraph that describes what we want without the duplication. In a comment box below please paste the two originals and then your merged version since it's important that @katb and @edwintse check that this composite paragraph adequately describes what was done.

**Comment by paulking1995** [comment]
3. looks fine to me? those graphs are showing two different things...S2 shows GC vs NMR while NMR Standard Curve.eps is used to standardise TCE with the product.

4. Working on it now.

**Comment by paulking1995** [comment]
okay, paragraphs have been combined
