### ISSUE TITLE
Inconsistency of standard OPS product m.p. with lit

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#30]
We mention that the m.p. of the product we obtain for compound 3 (the standard product) is not consistent with lit. We have good purity data on our compound, but is there anything else we need to say about this? Are there other m.p. values for this compound that _are_ consistent with our data? Are there other reports that are not consistent?

**Comment by paulking1995** [comment]
I will SciFinder this, there's a total of 7 reference so I'll check all of them.

**Comment by paulking1995** [comment]
We agree with one and disagree with one.

We agree with this:
"1-(4′-Nitrophenyl)-6,7-dimethoxyisochroman (15).
Mp: 138-140 °C. Yield: 77%. 1H NMR: 2.76 and 3.07 (2m,
2H, CH2-4), 3.66 and 3.88 (2s, 6H, OCH3-7 and OCH3-8), 3.89
and 4.12 (2m, 2H, CH2-3), 5.76 (s, 1H, H-1), 6.14 (s, 1H, H-6),
6.68 (s, 1H, H-9), 7.48-8.23 (m, 4H, Ar). Anal. (C17H17NO5)
C, H, N."
From: 10.1021/jm960506l

We disagree with this:
No characterisation data (no supporting information).
10.1016/j.cclet.2009.11.009

None of the other references (seven in total) are accessible or do not give a mp. So there are two in literature with a mp

**Comment by mattodd** [comment]
In @katb 's thesis she says that we're also inconsistent with this paper: B. Bouguerne, P. Hoffmann, and C. Lherbet. Bismuth Triflate as a Safe and Readily Handled Source of Triflic Acid: Application to the Oxa–Pictet–Spengler Reaction. Synth. Commun. 2010, 40, 915–926. Is this one of the seven you could not get @paulking1995 ?

For 10.1016/j.cclet.2009.11.009 how bad is the deviation?

It looks like we are citing both, rather inconsistently, in file Text S1 for compound 3 (refs 1 (in the data section) and 2 (at the end of the data)). Can we neaten this up, please? We need a concise form of words that compares our data with the lit m.p. values. Assigned to @paulking1995

**Comment by paulking1995** [comment]
I had access to that paper - that paper does NOT have a mp so I don't know why it was referenced for mp.

10.1016/j.cclet.2009.11.009 says 92-94

Just checked Kat's thesis, she cites 10.1016/j.cclet.2009.11.009 for the mp.

**Comment by paulking1995** [comment]
The different references for compound 3 are because they provide different data. [2] is for elemental analysis which [1] doesn't tell us. I have referenced the one we agree with because they actually have characterisation data while the other has just mp.

Closed.
