### ISSUE TITLE
Addition of Merck Data to the SI

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#31]
At the end of the current SI we make reference to the Merck SFC traces that were in Appendix E of your Hons thesis, @katb . These 11 PDF pages need to be saved as a separate file which we’ll call Figure SX (X to be determined) and upload separately from the S1 Text file. Is this in fact the current file called "Data from Merck", and so can we just rename it?

**Comment by edwintse** [comment]
"Data from Merck" has been renamed S1_Appendix.
