### ISSUE TITLE
Racemisation experiments

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#33]
@paulking1995 has determined that the Merck samples are still enantioenriched. Paul, you need to provide HPLC traces to show this that we will put in the SI.

We now need to select, and execute, a series of conditions where we evaluate racemisation. These ideally will use what @katb learned about the propensity to racemise. We can use this Issue to plan those conditions. So, what's first?

**Comment by paulking1995** [comment]
https://au-mynotebook.labarchives.com/share/Paul%2520King/NTA4LjN8NjMyMS8zOTEtMTY2Ni9UcmVlTm9kZS8zNDg4MzM0NzY0fDEyOTAuMw==

Merck HPLC traces are available here.

**Comment by mattodd** [comment]
Closing since we've carried out this experiments. BUT @paulking1995 **please take careful note** - we are going to need to ensure the relevant pages in your ELN that you used to derive these racemisation curves are public and that we have linked to them from the SI Text so readers can see what's what. We will address all this later, just before submission, but please put any pages relevant to racemisation into a public ELN section (folder?) where we can assemble the relevant pages.
