### ISSUE TITLE
Clarification of the Meaning of the Word "Conversion"

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#34]
@paulking1995  whenever this word is used, we need to clarify what we mean, as per previous discussion. "Conversion" can mean "how much *S/M* was converted" or it can mean "*product* yield by spectroscopy. I'd favour the latter. But we need clarity before we can submit.

**Comment by paulking1995** [comment]
Refers to how much S/M was converted (based on the limiting reagent and using the aldehyde peak takes priority when equal amounts of S/M)

**Comment by mattodd** [comment]
OK, @paulking1995 you need to check through the manuscript and check that the meaning (whenever this word is used) is clear. Flag up here anywhere where you think there may be ambiguity and we can deal with those. If the meaning is consistent throughout, do we need to insert a definition of the term (i.e. that it refers to how much S/M was converted) when it is first used?
