### ISSUE TITLE
Update on Section on Lewis Acids

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#35]
@katb has put in new text and new references and rejigged Fig 13, so it's currently on @mattodd to check.

**Comment by mattodd** [comment]
This looks good to me. However, @katb I think we need a little experimental description added to the file Text S1. i.e. some details of how this was all done from your thesis. Including any ligand synthesis that is relevant, the solvent system for the TLC method, etc.

**Comment by katb** [comment]
I've updated the SI to include experimental data for the LA section. Needs proofing for clarity and consistency. @paulking1995 @edwintse

**Comment by paulking1995** [comment]
Reviewed the SI. Closed.
