### ISSUE TITLE
Are we including any pictures of NMR spectra, or not?

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#38]
In the paper as it stands we say "Images of NMR spectra for all novel compounds are provided in Text S2" but we don't have any such file. So:

Are any of the products we describe novel? Do we therefore need to provide pictures of the NMR spectra? If yes, should we just include the relevant pictures in the upload to the USyd repo? In @katb 's TB paper we provide the spectra as separate image files - see the format [here](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0111782) which, for the reader, is more convenient. But we need clarity first on whether we need to provide data in this way for this paper.

**Comment by edwintse** [comment]
There are 6 novel compounds (not including any squaramide stuff Paul's done recently). @katb do you have the raw NMR files on hand?

I think it'll probably be easier to upload them to the repo.

**Comment by mattodd** [comment]
Do you have the compound numbers to hand, or are they identified as novel in the Compound Numbering cdx?

**Comment by edwintse** [comment]
They're colour-coded in the cdx

**Comment by mattodd** [comment]
Cross-reference to #32

**Comment by paulking1995** [comment]
I've added the squaramide to the Compound numbering file as 39 and it's a known compound but it's not novel.

**Comment by mattodd** [comment]
Just need "39" added to the Fig 14. This would mean that the squaramide and LA sections need to be switched.
