### ISSUE TITLE
Numbering of SI Figs

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#39]
There's a little confusion re numbering of the SI Figs. I'm pretty sure we should just agree on "Figure SX.eps" as the filename?

Regardless:

Figure S1 is GC standard curve. Fine
Figure S2 is meant to be NMR standard curve. I like the stacked plot, but as per #28 we need to combine this with the file called "NMR Standard Curve" to make sure we all agree on a single figure. Address that over at #28 not here.
Figure S3 is currently a nice 1H NMR spectrum of everything together to show integrals/baseline sep. I don't think we refer to this anywhere? If not, we should. **Action: insert a tag for this figure in a suitable place, somewhere in the Reaction Yield Assays section.** Needs to be between Fig S2 and S4, obv. Assigning @edwintse 
What was Figure S4 in Dropbox is the graph showing that order of addition matters, glass vs borosoilicate etc. In the paper it's referred to as Figure S5. **I have renamed this Figure S6 in both the paper and the file.**
What was Figure S5 is the HSQC, but this is referred to as Figure S3 in the paper. **I have renamed this Figure S4**
What was Figure S6 is HMBC but is referred to as Figure S4 in paper. I **have renamed this Figure S5.**

**Comment by mattodd** [comment]
Hi @edwintse this also means renumbering of the items at the end of the paper a little bit.

**Comment by edwintse** [comment]
Ok, things are renamed/renumbered.
Leaving Figure S2 for the moment. 
Not really sure where to add in Figure S3. Everything seems to be described in Figure S2. Maybe putting something like "The corresponding signals of reagents/product/standard from the crude reaction mixture are shown in Figure S3"?

**Comment by mattodd** [comment]
Yes something like that. It's still a useful figure, I think. Can you please insert and then close this?

**Comment by edwintse** [comment]
Added as above. Renaming HSQC to Figure S3, HMBC to Figure S4 and what was Figure S3 to Figure S5.
