### ISSUE TITLE
Complete Merck Author List Additions

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#4]
Need names of people who assisted from Merck, added to paper in alphabetical order.

**Comment by katb** [comment]
Sent query email to Merck, waiting for reply

**Comment by mattodd** [comment]
OK, @katb can we please clarify: Amanda Makarewicz and Lisa Frey? Both? And address is:

Merck & Co., East Lincoln Ave, Rahway, NJ  07065, USA?

If yes, can you please add this to the paper on Overleaf and close this issue? If anything needs further action, keep this issue open.

**Comment by katb** [comment]
I've emailed Amanda to clarify the address

**Comment by katb** [comment]
Clarified authorship issue with Amanda and Lisa via email correspondence. To include Amanda, who did the work.
