### ISSUE TITLE
Wavelength for chiral HPLC, other little things in chiral HPLC section

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#40]
...is 280 nm in paper (which I'm deleting as too much info) but 208 nm in SI Text (where the number needs to be). If the 208 is meant to be 280, please change in the SI Text doc @paulking1995 

Also in that section of the SI there are references to compounds 1 and 2...? There are a number of other little things that also need fixing. Highlighted in red. Once all taken care of, please close this issue.

**Comment by paulking1995** [comment]
For the standard compound, the mp is consistent with literature except for one case - it seems that paper got it wrong somewhere since everyone else agrees with our result. Therefore, that's no longer relevant.

The rest is fixed.

Closed.

**Comment by mattodd** [comment]
Fix up synthesis of squaramide section
