### ISSUE TITLE
Squaramide section

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#41]
This needs more - 3-4 sentences. Why are we doing it (finding "less acidic" conditions) and what were the results? i.e. describe in words what the figure says. What do the results imply, and hence what would be the next step by the community?

**Comment by mattodd** [comment]
Also can we make a comment on what is seen with squaramide alone? We've shown HCl alone in the figure.

**Comment by paulking1995** [comment]
Added new text.

Talked about desiring milder conditions for enantioselectivity, addition of squaramides shows appeciable conversion while absence showed only trace conversion at room temp, and further optimisation will be needed and large screening efforts to attain desired enantioselectivity.

Closed.
