### ISSUE TITLE
Graphical Abstract

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#5]
Need draft graphical abstract images for paper. Files should go on Github within "Figures". Suggestions welcome...

**Comment by mattodd** [comment]
Uploaded graphical abstract v2 chemdraw to both this repo and Dropbox. Please tinker/improve and save as v3 etc if you do. No changes means we'll use as-is.

**Comment by paulking1995** [comment]
I assume at this point, we will use as is.
