### ISSUE TITLE
Rewrite two sentences in paragraph starting “The GC and NMR assays…”

### ISSUE THREAD

**Issue by mattodd** [opensourcecatalysis/OPS-Paper1#9]
Notes in paper. Close when done.

**Comment by paulking1995** [comment]
Regarding the equation, it is stated that the equation gives the number of moles. If you want percentage yield, you can divide that equation by the moles of the limiting reagent.

**Comment by paulking1995** [comment]
With regards to the purity measurements, the recommendation is to run qNMR (ie d1=60) against an internal standard (eg dimethyl sulfone is a common one).

**Comment by paulking1995** [comment]
With regards to the NMR graph, the inconsistency comes from whether it's fixed at origin or not. Since we don't use the y-intercept value, I think it should be fixed at origin. @edwintse would you be able to change the greaph so it's fixed at origin? Once it's fixed at origin, slope should be 0.924

**Comment by paulking1995** [comment]
As for the repeated paragraph - there's a bit of overlap but the first one is more towards the decision making while the second actually explains what was performed

**Comment by mattodd** [comment]
Transferred remaining things to #28 - @paulking1995 try to keep discussion of issues tightly connected to the original issue.
